language: php
php:
  - '7.2'
  - '7.3'
  - '7.4

before_script:
  - composer install --ignore-platform-reqs

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)